### ISSUE TITLE
Plugin de Compartilhamento nas Redes

### ISSUE THREAD

**Issue by iwasthesword** [redelivre/redelivre#109]
Plugin de compartilhamento em redes socias com uma boa customização e inclue whatsapp.

https://br.wordpress.org/plugins/add-to-any/

**Comment by jacsonp** [comment]
@iwasthesword Usar o monarch não rola, é o plugin proposto para isso, vamos abondonar no Monarch e partir para esse aí? é mais fácil?

**Comment by uira** [comment]
@jacsonp Rola, mas queremos justamente testar e comparar os dois.

**Comment by iwasthesword** [comment]
@jacsonp eu achei o Add to Any mais versatil por ser menos carregado de css, por ter um shortcode bem facil de usar e por também conter o compartilhamento por whatsapp que é uma função dificil de achar em outros plugins.

**Comment by raissagal** [comment]
Não está contabilizando os shares no beta

**Comment by iwasthesword** [comment]
@raissagal isso é opção interna do plugin, é só mudar lá!

Tenho testado nos ultimos dias lá no beta e ta rodando liso, sem erro

**Comment by jacsonp** [comment]
está no ar, está aprovado, posso fechar?

**Comment by iwasthesword** [comment]
@jacsonp pode! ta rolando legal
