### ISSUE TITLE
Bug no tema Rede Ninja

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/redelivre#126]
Este bug rolou no http://projetodetestes.beta.redelivre.org.br ao ativar o tema Rede Ninja - e aí eu não consegui mais sair desta tela.
![redeninja1](https://cloud.githubusercontent.com/assets/2422926/26508375/d920b186-422a-11e7-97c1-234212da84a2.png)

E este, que me parece diferente, tá na capa do http://redeninja.beta.redelivre.org.br/
![redenunja2](https://cloud.githubusercontent.com/assets/2422926/26508383/e179b3aa-422a-11e7-9d93-bb2021b8b287.png)

**Comment by jacsonp** [comment]
na verdade o bug é do delibera, as funções deveriam ter namespace ou prefixo 'delibera_'
