### ISSUE TITLE
Problema em Contato

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/redelivre#29]
Quando não tem o template de contato a página fica em branco. Isso acontece nos temas Quizumba e Kaigang.

**Comment by uira** [comment]
Sugestão de Melhoria: 

- [ ] Desativar Página de Contato da RedeLIvre, tirar do menu e tirar a funcionalidade.

**Justificativa:** O Bug relatado acima, e opções mais robustas de página de contato, nos temas, no CF7 e no próprio JetPack que tá sendo proposto.

**Comment by jacsonp** [comment]
fixed at 25b5fd1101a1a78db8e5bffb14e06f19b050b8f7

**Comment by jacsonp** [comment]
@uira se quiser desativar vai ter que criar outra issue
