### ISSUE TITLE
Webcontatos - Erro ao subir arquivo

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/redelivre#52]
Utilizando o webcontatos em http://forumsocialportoalegre.org.br, ao tentar subir um arquivo em CSV, apresenta o seguinte erro:

![bug webcontatos](https://cloud.githubusercontent.com/assets/2422926/7138364/4f414e8a-e296-11e4-9589-6a0989ea4488.png)

**Comment by jacsonp** [comment]
Na tela aparece como se você não tivesse selecionado nenhum arquivo.

**Comment by anapaulabrasa** [comment]
Mas foi selecionado. Testei novsmente, e nesta mesma tela.

**Comment by jpmehl** [comment]
já testou com ODT \?

Em 14 de abril de 2015 11:17, anapaulabrasa <notifications@github.com>
escreveu:

> Mas foi selecionado. Testei novsmente, e nesta mesma tela.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redelivre/redelivre/issues/52#issuecomment-92868269>.
>



-- 
João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9627-5518
