### ISSUE TITLE
Abrir o Gitter da redelivre

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/redelivre#54]
Galera, o @jpmehl listou no READAME.md o link para usarmos o Gitter em conversas mais informais sobre a redelivre. No entanto, ela só permite que membros da organização deem seus pitacos.

Pensei então que seria ideal que abríssemos a comunicação, e para isso criei um canal aberto chamado [redelivre/emrede](https://gitter.im/redelivre/emrede?utm_source=share-link&utm_medium=link&utm_campaign=share-link).

Que tal usarmos ele?

**Comment by anapaulabrasa** [comment]
da hora, edu

Em 22 de julho de 2015 23:27, Eduardo Zulian <notifications@github.com>
escreveu:

> Galera, o @jpmehl <https://github.com/jpmehl> listou no READAME.md o link
> para usarmos o Gitter em conversas mais informais sobre a redelivre. No
> entanto, ela só permite que membros da organização deem seus pitacos.
>
> Pensei então que seria ideal que abríssemos a comunicação, e para isso
> criei um canal aberto chamado redelivre/emrede
> <https://gitter.im/redelivre/emrede?utm_source=share-link&utm_medium=link&utm_campaign=share-link>
> .
>
> Que tal usarmos ele?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redelivre/redelivre/issues/54>.
>



-- 
Ana Paula Salamon
Ethymos Soluções em Web
www.ethymos.com.br
(41) 3077-4163

**Comment by eduardozulian** [comment]
Já iniciamos os trabalhos por lá!
