### ISSUE TITLE
Nome do tema da redelivre

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/redelivre#56]
Precisamos de um repositório novo para o tema da redelivre.

Minha ideia: poderíamos tentar seguir um nome que se encaixe com a identidade criada pela @thalitasejanes 

Joguem ideias!

**Comment by jpmehl** [comment]
Massa Edu.
Manda a identidade Thalita ;)
Em 30/07/2015 12:06, "Eduardo Zulian" <notifications@github.com> escreveu:

**Comment by eduardozulian** [comment]
Fechando porque o nome foi decidido (Fluxo) em outra conversa.

Precisamos documentar melhor as coisas.
