### ISSUE TITLE
Twitter Tracker

### ISSUE THREAD

**Issue by ElidiaVidal** [redelivre/redelivre#93]
- [ ] Não está clara para que serve essa ferramenta. Poderia estar em português e/ou com um texto explicativo sobre “para que serve” e “como utilizar”.
- [x] Desabilitar como padrão.
![photo_2017-03-29_22-48-21](https://cloud.githubusercontent.com/assets/26146292/24516482/2b001048-1551-11e7-99f5-d8697baa8169.jpg)

**Comment by uira** [comment]
Plugin Desativado!
